services:
    therminator_os:
        build: .
        privileged: true
        stdin_open: true
        tty: true
        image: therminator_os:latest
        volumes:
            - ./ext_dir:/home/imagegen/ext_dir