#!/bin/bash
set -eu

cat <<EOF > "$1/etc/systemd/system/lingering-setup.service"
[Unit]
Description=Enable lingering for therminator
After=multi-user.target
ConditionPathExists=!/var/lib/systemd/linger/therminator

[Service]
Type=oneshot
ExecStart=/bin/loginctl enable-linger therminator
ExecStartPost=/bin/systemctl disable lingering-setup.service
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF

ln -sf /etc/systemd/system/lingering-setup.service "$1/etc/systemd/system/multi-user.target.wants/lingering-setup.service"

# Add polkit rule to allow udisks2 operations without password for plugdev group
cat <<EOF > "$1/etc/polkit-1/rules.d/10-udisks2.rules"
polkit.addRule(function(action, subject) {
  if ((action.id == "org.freedesktop.udisks2.filesystem-mount" ||
       action.id == "org.freedesktop.udisks2.filesystem-unmount-others" ||
       action.id == "org.freedesktop.udisks2.encrypted-unlock" ||
       action.id == "org.freedesktop.udisks2.eject-media") &&
      subject.isInGroup("plugdev")) {
    return polkit.Result.YES;
  }
});
EOF


# Create the systemd service template to mount USB drives as the user 'therminator'
cat <<EOF > "$1/etc/systemd/system/usb-mount@.service"
[Unit]
Description=USB Automount for device %i
After=graphical.target
Requires=dbus.service
StartLimitIntervalSec=30
StartLimitBurst=5

[Service]
User=therminator
ExecStart=/usr/local/bin/usb-mount.sh %i
Restart=on-failure
EOF

cat <<EOF > "$1/etc/udev/rules.d/99-usb-mount.rules"
ACTION=="add", KERNEL=="sd[a-z][0-9]", TAG+="systemd", ENV{SYSTEMD_WANTS}="usb-mount@%k.service"
ACTION=="remove", KERNEL=="sd[a-z][0-9]", RUN+="/usr/local/bin/usb-umount.sh %k"
EOF
# Ensure the /media directory exists and is writable
mkdir -p "$1/media"
chmod 777 "$1/media"

$BDEBSTRAP_HOOKS/enable-units "$1" systemd-udevd
$BDEBSTRAP_HOOKS/enable-units "$1" dbus
$BDEBSTRAP_HOOKS/enable-units "$1" udisks2