#!/bin/bash

set -eu

# configure the splashscreen
mkdir -p $1/usr/share/plymouth/themes/corintis
chmod 755 $1/usr/share/plymouth/themes/corintis

rsync -a ${IGIMAGE}/plymouth/themes/corintis $1/usr/share/plymouth/themes/

chmod 644 $1/usr/share/plymouth/themes/corintis/*

# set the default theme to corintis
chroot $1 plymouth-set-default-theme corintis 